branches:
    only:
        - master

language: node_js

node_js:
    - "10"

script:
    - echo "Deploy"

install:
    - npm install -g firebase-tools
    - yarn install

after_success:
    - yarn build
    - firebase deploy --project emroni-website --token $FIREBASE_TOKEN