branches:
    only:
        - master

language: node_js

node_js:
    - "10"

install:
    - npm install -g firebase-tools
    - yarn install

script:
    - yarn build
    - firebase deploy --project $FIREBASE_PROJECT --token $FIREBASE_TOKEN